---

- name: set group
  group:
    name: "{{ group.name }}"
    gid: "{{ group.gid | default(omit) }}"
    system: "{{ group.system | default('no') }}"
    state: "{{ group.present | default('present') }}"

- name: set user
  user:
    name: "{{ user.name }}"
    uid: "{{ user.uid | default(omit) }}"
    comment: "{{ user.comment }}"
    create_home: "{{ user.create_home | default(omit) }}"
    home: "{{ user.home | default(omit) }}"
    force: yes
    group: "{{ user.group }}"
    groups: "{{ user.groups | default(omit) }}"
    shell: "{{ user.shell | default('/usr/sbin/nologin') }}"
    password: "{{ user.password | default(omit) }}"
    state: "{{ user.state | default('present') }}"

- name: add authorized_keys
  authorized_key:
    user: "{{ user.name }}"
    key: "{{ user.ssh_authorized_key }}"
    state: "{{ user.authorized_key_state | default('present') }}"
  when: user.ssh_authorized_key is defined and user.ssh_authorized_key

- name: deploy shell environments
  template:
    src: "skel/{{ item }}"
    dest: "{{ user.home }}/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: "0600"
  loop:
    - .profile
    - .bashrc
    - .bash_profile
    - .zprofile
    - .zshrc
  failed_when: no
  when: user.home is defined
