---

- name: set password
  set_fact:
    _kea_ctrl_agent_password_defined: "{{ lookup('vars', 'kea_api_' + _kea_ctrl_agent_client.user + '_password') if ('kea_api_' + _kea_ctrl_agent_client.user + '_password') in vars else '' }}"


- block:

    - name: check kea ctrl agent password file
      stat:
        path: "{{ kea_conf_dir }}/{{ _kea_ctrl_agent_client['password-file'] }}"
      register: _kea_ctrl_agent_password_file_stat

    - block:

        - name: create kea ctrl agent password
          set_fact:
            _kea_ctrl_agent_password_defined: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'digits'], length=16) }}"

      when: not _kea_ctrl_agent_password_file_stat.stat.exists

  when: not _kea_ctrl_agent_password_defined


- block:

    - name: deploy kea ctrl agent password file
      copy:
        content: "{{ _kea_ctrl_agent_password_defined }}"
        dest: "{{ kea_conf_dir }}/{{ _kea_ctrl_agent_client['password-file'] }}"
        owner: "{{ kea_admin_user | d('root') }}"
        group: "{{ kea_group }}"
        mode: "0640"
      notify:
        - "{{ kea_service_type }} restart kea ctrl-agent"

  when: _kea_ctrl_agent_password_defined
