---

- block:
    - include_tasks: context.yml

    - include_tasks: common.yml

    - include_tasks: package.yml

    - include_tasks: security.yml

    - include_tasks: dhcp4.yml

    - include_tasks: dhcp6.yml

    - include_tasks: ddns.yml

    - include_tasks: keactrl.yml

    - include_tasks: ctrl_agent.yml

  when: want_kea

- name: set has_kea
  set_fact:
    has_kea: "{{ want_kea }}"
