---

- block:
    - include_tasks: context.yml

    - include_tasks: setup_vars.yml

    - include_tasks: setup_workspace.yml

    - include_tasks: setup_distribution.yml

    - include_tasks: setup_configuration.yml

    - include_tasks: setup_protection.yml

    - include_tasks: setup_service.yml

  when: want_kea

- name: set has_kea
  set_fact:
    has_kea: "{{ want_kea }}"
