---

- name: apt install
  block:
    - apt:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
        autoclean: yes

  when: ansible_pkg_mgr == 'apt'


- name: yum install
  block:
    - yum:
        name: "{{ packages }}"
        state: latest
        update_cache: yes

  when: ansible_pkg_mgr == 'yum'

- name: pkg install
  block:
    - pkgng:
        name: "{{ packages }}"
        state: latest
  when: ansible_pkg_mgr == 'pkgng'
