---

- name: deploy keactrl.conf
  template:
    src: "conf/keactrl.conf"
    dest: "{{ kea_ctrl_conf_path }}"
    owner: "{{ kea_admin_user | d('root') }}"
    group: "{{ kea_group }}"
    mode: "0640"
  register: t_kea_conf_kea_ctrl


- name: deploy kea-netconf.conf
  template:
    src: "conf/kea-netconf.conf"
    dest: "{{ kea_netconf_conf_path }}"
    owner: "{{ kea_admin_user | d('root') }}"
    group: "{{ kea_group }}"
    mode: "0640"
  register: t_kea_conf_kea_netconf
  when: kea_want_netconf


- block:
    - name: kea-dhcp4 - load base
      set_fact:
        kea_dhcp4_conf_base_content: "{{ lookup('template', 'conf/' + kea_dhcp4_conf_name) }}"

    - name: kea-dhcp4 - stat current conf
      stat:
        path: "{{ kea_dhcp4_conf_path }}"
      register: t_kea_dhcp4_conf_stat

    - block:
        - name: kea-dhcp4 - load current conf
          slurp:
            src: "{{ t_kea_dhcp4_conf_stat.stat.path }}"
          register: t_kea_dhcp4_conf_current

        - name: kea-dhcp4 - set conf content
          set_fact:
            t_kea_dhcp4_conf_content: "{{ t_kea_dhcp4_conf_current ['content'] | b64decode | from_json | combine(kea_dhcp4_conf_base_content, list_merge='append_rp', recursive='true') | to_json(indent=4) }}"
          ignore_errors: yes

        - name: kea-dhcp4 - set conf content
          set_fact:
            t_kea_dhcp4_conf_content: "{{ kea_dhcp4_conf_base_content | to_json(indent=4) }}"
          when: t_kea_dhcp4_conf_content is not defined

        - name: kea-dhcp4 - update current conf
          copy:
            dest: "{{ t_kea_dhcp4_conf_stat.stat.path }}"
            content: "{{ t_kea_dhcp4_conf_content }}"
            owner: "{{ kea_admin_user | d('root') }}"
            group: "{{ kea_group }}"
            mode: "0640"
          register: t_kea_conf_kea_dhcp4

      when: t_kea_dhcp4_conf_stat.stat.exists

    - name: kea-dhcp4 - deploy conf
      copy:
        dest: "{{ kea_dhcp4_conf_path }}"
        content: "{{ kea_dhcp4_conf_base_content | to_json(indent=4) }}"
        owner: "{{ kea_admin_user | d('root') }}"
        group: "{{ kea_group }}"
        mode: "0640"
      register: t_kea_conf_kea_dhcp4
      when: not t_kea_dhcp4_conf_stat.stat.exists

  when: kea_want_dhcp4


- block:
    - name: kea_dhcp6 - load base
      set_fact:
        kea_dhcp6_conf_base_content: "{{ lookup('template', 'conf/' + kea_dhcp6_conf_name) }}"

    - name: kea_dhcp6 - stat current conf
      stat:
        path: "{{ kea_dhcp6_conf_path }}"
      register: t_kea_dhcp6_conf_stat

    - block:
        - name: kea_dhcp6 - load current conf
          slurp:
            src: "{{ t_kea_dhcp6_conf_stat.stat.path }}"
          register: t_kea_dhcp6_conf_current

        - name: kea-dhcp6 - set conf content
          set_fact:
            t_kea_dhcp6_conf_content: "{{ t_kea_dhcp6_conf_current ['content'] | b64decode | from_json | combine(kea_dhcp6_conf_base_content, list_merge='append_rp', recursive='true') | to_json(indent=4) }}"
          ignore_errors: yes

        - name: kea-dhcp6 - set conf content
          set_fact:
            t_kea_dhcp6_conf_content: "{{ kea_dhcp6_conf_base_content | to_json(indent=4) }}"
          when: t_kea_dhcp6_conf_content is not defined

        - name: kea_dhcp6 - update current conf
          copy:
            dest: "{{ t_kea_dhcp6_conf_stat.stat.path }}"
            content: "{{ t_kea_dhcp6_conf_content }}"
            owner: "{{ kea_admin_user | d('root') }}"
            group: "{{ kea_group }}"
            mode: "0640"
          register: t_kea_conf_kea_dhcp6

      when: t_kea_dhpc6_conf_stat.stat.exists

    - name: kea_dhcp6 - deploy conf
      copy:
        dest: "{{ kea_dhcp6_conf_path }}"
        content: "{{ kea_dhcp6_conf_base_content | to_json(indent=4) }}"
        owner: "{{ kea_admin_user | d('root') }}"
        group: "{{ kea_group }}"
        mode: "0640"
      register: t_kea_conf_kea_dhcp6
      when: not t_kea_dhcp6_conf_stat.stat.exists

  when: kea_want_dhcp6


- block:
    - name: kea_dhcp_ddns - load base
      set_fact:
        kea_dhcp_ddns_conf_base_content: "{{ lookup('template', 'conf/' + kea_dhcp_ddns_conf_name) }}"

    - name: kea_dhcp_ddns - stat current conf
      stat:
        path: "{{ kea_dhcp_ddns_conf_path }}"
      register: t_kea_dhcp_ddns_conf_stat

    - block:
        - name: kea_dhcp_ddns - load current conf
          slurp:
            src: "{{ t_kea_dhcp_ddns_conf_stat.stat.path }}"
          register: t_kea_dhcp_ddns_conf_current

        - name: kea_dhcp_ddns - set conf content
          set_fact:
            t_kea_dhcp_ddns_conf_content: "{{ t_kea_dhcp_ddns_conf_current | b64decode | from_json | combine(kea_dhcp_ddns_conf_base_content, list_merge='append_rp', recursive='true') | to_json(indent=4) }}"
          ignore_errors: yes

        - name: kea_dhcp_ddns - set conf content
          set_fact:
            t_kea_dhcp_ddns_conf_content: "{{ kea_dhcp_ddns_conf_base_content | to_json(indent=4) }}"
          when: t_kea_dhcp_ddns_conf_content is not defined

        - name: kea_dhcp_ddns - update current conf
          copy:
            dest: "{{ t_kea_dhcp_ddns_conf_stat.stat.path }}"
            content: "{{ t_kea_dhcp_ddns_conf_content }}"
            owner: "{{ kea_admin_user | d('root') }}"
            group: "{{ kea_group }}"
            mode: "0640"
          register: t_kea_conf_kea_dhcp_ddns

      when: t_kea_dhcp_ddns_conf_stat.stat.exists

    - name: kea_dhcp_ddns - deploy conf
      copy:
        dest: "{{ kea_dhcp_ddns_conf_path }}"
        content: "{{ kea_dhcp_ddns_conf_base_content | to_json(indent=4) }}"
        owner: "{{ kea_admin_user | d('root') }}"
        group: "{{ kea_group }}"
        mode: "0640"
      register: t_kea_conf_kea_dhcp_ddns
      when: not t_kea_dhcp_ddns_conf_stat.stat.exists

  when: kea_want_dhcp_ddns


- block:
    - name: kea-ctrl-agent - load base
      set_fact:
        kea_ctrl_agent_conf_base_content: "{{ lookup('template', 'conf/' + kea_ctrl_agent_conf_name) }}"

    - name: kea-ctrl-agent - stat current conf
      stat:
        path: "{{ kea_ctrl_agent_conf_path }}"
      register: t_kea_ctrl_agent_conf_stat

    - block:
        - name: kea-ctrl-agent - load current conf
          slurp:
            src: "{{ t_kea_ctrl_agent_conf_stat.stat.path }}"
          register: t_kea_ctrl_agent_conf_current

        - name: kea-ctrl-agent - set conf content
          set_fact:
            t_kea_ctrl_agent_conf_content: "{{ t_kea_ctrl_agent_conf_current['content'] | b64decode | from_json | combine(kea_ctrl_agent_conf_base_content, list_merge='append_rp', recursive='true') | to_json(indent=4) }}"
          ignore_errors: yes

        - name: kea-ctrl-agent - set conf content
          set_fact:
            t_kea_ctrl_agent_conf_content: "{{ kea_ctrl_agent_conf_base_content | to_json(indent=4) }}"
          when: t_kea_ctrl_agent_conf_content is not defined

        - name: kea-ctrl-agent - update current conf
          copy:
            dest: "{{ t_kea_ctrl_agent_conf_stat.stat.path }}"
            content: "{{ t_kea_ctrl_agent_conf_content }}"
            owner: "{{ kea_admin_user | d('root') }}"
            group: "{{ kea_group }}"
            mode: "0640"
          register: t_kea_conf_kea_ctrl_agent

      when: t_kea_ctrl_agent_conf_stat.stat.exists

    - name: kea-ctrl-agent - deploy conf
      copy:
        dest: "{{ kea_ctrl_agent_conf_path }}"
        content: "{{ kea_ctrl_agent_conf_base_content | to_json(indent=4) }}"
        owner: "{{ kea_admin_user | d('root') }}"
        group: "{{ kea_group }}"
        mode: "0640"
      register: t_kea_conf_kea_ctrl_agent
      when: not t_kea_ctrl_agent_conf_stat.stat.exists

  when: kea_want_ctrl_agent


- name: "check {{ kea_ctrl_agent_conf_password_file }}"
  stat:
    path: "{{ kea_ctrl_agent_conf_password_file_path }}"
  register: t_kea_ctrl_agent_conf_password_file_stat

- name: "create random password for kea-api user"
  set_fact:
    kea_ctrl_agent_conf_password: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'digits'], length=16) }}"
  when:
    - kea_ctrl_agent_conf_password is not defined
    - not t_kea_ctrl_agent_conf_password_file_stat.stat.exists

- block:
    - name: "reload password for kea-api user"
      slurp:
        src: "{{ kea_ctrl_agent_conf_password_file_path }}"
      register: t_kea_ctrl_agent_conf_password

    - name: "set password for kea-api user"
      set_fact:
        kea_ctrl_agent_conf_password: "{{ t_kea_ctrl_agent_conf_password['content'] | b64decode }}"

  when:
    - kea_ctrl_agent_conf_password is not defined
    - t_kea_ctrl_agent_conf_password_file_stat.stat.exists

- name: "deploy {{ kea_ctrl_agent_conf_password_file }}"
  copy:
    content: "{{ kea_ctrl_agent_conf_password }}"
    dest: "{{ kea_ctrl_agent_conf_password_file_path }}"
    owner: "{{ kea_admin_user | d('root') }}"
    group: "{{ kea_group }}"
    mode: "0640"
