---

### use_package: yes

- block:
    - name: remove link to kea build
      file:
        path: "{{ kea_build_in_use }}"
        state: absent

    - name: install packages
      include_tasks: package_installer.yml
      vars:
        packages: "{{ kea_packages | d(kea_default_packages) }}"

    - name: set kea_bin_base_path
      set_fact:
        kea_bin_base_path: "{{ path_package_base }}"

  when: not kea_build


### use_package: no

- block:
    - include_tasks: directory_tree.yml
      vars:
        directory_tree: "{{ kea_build_directory_tree }}"

    - name: check current build status
      command:
        cmd: "{{ kea_build_current }}/sbin/keactrl --version"
      become: yes
      become_user: "{{ kea_user }}"
      changed_when: no
      failed_when: no
      register: t_kea_check_build_status

    - block:
        - name: install requirements
          include_tasks: package_installer.yml
          vars:
            packages: "{{ kea_build_packages | d(kea_build_defaut_packages[ansible_distribution]) | d(kea_build_defaut_packages[ansible_system]) }}"

        - name: download kea archive
          get_url:
            url: "{{ kea_archive_url }}"
            dest: "{{ kea_distfiles }}/{{ kea_archive }}"
            owner: "{{ kea_admin_user|d('root') }}"
            group: "{{ kea_group }}"
            mode: '0640'

        - name: build tmp directory
          tempfile:
            path: "{{ kea_build_dir}}"
            state: directory
            prefix: temp
          register: build_dir
          become: yes
          become_user: "{{ kea_admin_user|d('root') }}"

        - name: extract archive
          unarchive:
            src: "{{ kea_distfiles }}/{{ kea_archive }}"
            dest: "{{ build_dir.path }}"
            remote_src: yes
            owner: "{{ kea_admin_user|d('root') }}"
            group: "{{ kea_group }}"

        - name: build kea
          shell:
            cmd: "{{ kea_build_command }}"
          args:
            chdir: "{{ build_dir.path }}/kea-{{ kea_version }}"
          become: yes
          become_user: "{{ kea_admin_user|d('root') }}"

        - name: clean build tmp directory
          file:
            path: "{{ build_dir.path }}"
            state: absent

      when: t_kea_check_build_status.rc != 0 or t_kea_check_build_status.stdout != kea_version

    - name: link to kea build to use
      file:
        src: "{{ kea_build_current }}"
        dest: "{{ kea_build_in_use }}"
        owner: "{{ kea_admin_user|d('root') }}"
        group: "{{ kea_group }}"
        state: link

    - name: set kea_bin_base_path
      set_fact:
        kea_bin_base_path: "{{ kea_build_in_use }}"

  when: kea_build
