---

- include_tasks: try_zfs.yml
  vars:
    dataset:
      name: "{{ kea_service_dir }}"

- include_tasks: add_user.yml
  vars:
    group:
      name: "{{ kea_group }}"
      gid: "{{ kea_gid }}"
    user:
      name: "{{ kea_user }}"
      comment: "{{ kea_name }}"
      group: "{{ kea_group }}"
      groups: "{{ kea_groups }}"
      home: "{{ kea_home }}"
      shell: "{{ kea_shell }}"
      uid: "{{ kea_uid }}"
      home_mode: "{{ kea_home_mode }}"
      password: '*'

- include_tasks: directory_tree.yml
  vars:
    directory_tree:
      - path: "{{ kea_service_dir }}"
        owner: "{{ kea_admin_user | d('root') }}"
        group: "{{ kea_group }}"
        mode: "0750"
  when: kea_service_dir != kea_home

- include_tasks: directory_tree.yml
  vars:
    directory_tree:
      - path: "{{ kea_home }}"
        owner: "{{ kea_user }}"
        group: "{{ kea_group }}"
        mode: "0700"
      - path: "{{ kea_conf_dir }}"
        owner: "{{ kea_admin_user | d('root') }}"
        group: "{{ kea_group }}"
        mode: "0750"
      - path: "{{ kea_log_dir }}"
        owner: "{{ kea_user }}"
        group: "{{ kea_group }}"
        mode: "{{ kea_log_dir_mode | d('0750') }}"
      - path: "{{ kea_run_dir }}"
        owner: "{{ kea_user }}"
        group: "{{ kea_group }}"
        mode: "{{ kea_run_dir_mode }}"
      - path: "{{ kea_run_lock_dir }}"
        owner: "{{ kea_user }}"
        group: "{{ kea_group }}"
        mode: "{{ kea_run_lock_dir_mode | d('0755') }}"
      - path: "{{ kea_db_dir }}"
        owner: "{{ kea_user }}"
        group: "{{ kea_group }}"
        mode: "{{ kea_db_dir_mode | d('0755') }}"
      - path: "{{ kea_var_dir }}"
        owner: "{{ kea_user }}"
        group: "{{ kea_group }}"
        mode: "{{ kea_var_dir_mode | d('0755') }}"
