---

# systemd

- block:

  # disable extra
  - name: disable extra service name
    systemd:
      name: "{{ item }}"
      enabled: no
      state: stopped
      daemon_reload: true
    loop: "{{ kea_service_to_disable }}"


  # systemd : kea-ctrl-agent
  - name: configure kea-ctrl-agent service through systemd
    block:
      - name: deploy systemd service kea-ctrl-agent
        template:
          src: "systemd/kea-ctrl-agent.service"
          dest: "{{ systemd_system_lib_dir }}/{{ kea_ctrl_agent_service_name }}.service"
          owner: "{{ root }}"
          group: "{{ root_group }}"
          mode: "0644"
        register: t_kea_service_ctr_agent_conf

      - name: activate systemd service
        systemd:
          name: "{{ kea_ctrl_agent_service_name }}.service"
          enabled: "{{ kea_want_ctrl_agent }}"
          state: "{{ kea_want_ctrl_agent | ternary('started', 'stopped') }}"
          masked: no
          daemon_reload: true

      - name: reload systemd service
        systemd:
          name: "{{ kea_ctrl_agent_service_name }}.service"
          state: restarted
          daemon_reload: true
        when: kea_want_ctrl_agent and (t_kea_service_ctr_agent_conf.changed or t_kea_conf_kea_ctrl_agent.changed)


  # systemd : kea-dhcp4
  - name: configure kea-dhcp4 service through systemd
    block:
      - name: deploy systemd service kea-dhcp4
        template:
          src: "systemd/kea-dhcp4.service"
          dest: "{{ systemd_system_lib_dir }}/{{ kea_dhcp4_service_name }}.service"
          owner: "{{ root }}"
          group: "{{ root_group }}"
          mode: "0644"
        register: t_kea_service_dhcp4_conf

      - name: activate systemd service
        systemd:
          name: "{{ kea_dhcp4_service_name }}.service"
          enabled: "{{ kea_want_dhcp4 }}"
          state: "{{ kea_want_dhcp4 | ternary('started', 'stopped') }}"
          masked: no
          daemon_reload: true

      - name: reload systemd service
        systemd:
          name: "{{ kea_dhcp4_service_name }}.service"
          state: restarted
          daemon_reload: true
        when: kea_want_dhcp4 and (t_kea_service_dhcp4_conf.changed or t_kea_conf_kea_dhcp4.changed)


  # systemd : kea-dhcp6
  - name: configure kea-dhcp6 service through systemd
    block:
      - name: deploy systemd service kea-dhcp6
        template:
          src: "systemd/kea-dhcp6.service"
          dest: "{{ systemd_system_lib_dir }}/{{ kea_dhcp6_service_name }}.service"
          owner: "{{ root }}"
          group: "{{ root_group }}"
          mode: "0644"
        register: t_kea_service_dhcp6_conf

      - name: activate systemd service
        systemd:
          name: "{{ kea_dhcp6_service_name }}.service"
          enabled: "{{ kea_want_dhcp6 }}"
          state: "{{ kea_want_dhcp6 | ternary('started', 'stopped') }}"
          masked: no
          daemon_reload: true

      - name: reload systemd service
        systemd:
          name: "{{ kea_dhcp6_service_name }}.service"
          state: restarted
          daemon_reload: true
        when: kea_want_dhcp6 and (t_kea_service_dhcp6_conf.changed or t_kea_conf_kea_dhcp6.changed)


  # systemd : kea-ddns
  - name: configure kea-ddns service through systemd
    block:
      - name: deploy systemd service kea-ddns
        template:
          src: "systemd/kea-dhcp-ddns.service"
          dest: "{{ systemd_system_lib_dir }}/{{ kea_dhcp_ddns_service_name }}.service"
          owner: "{{ root }}"
          group: "{{ root_group }}"
          mode: "0644"
        register: t_kea_service_ddns_conf

      - name: activate systemd service
        systemd:
          name: "{{ kea_dhcp_ddns_service_name }}.service"
          enabled: "{{ kea_want_dhcp_ddns }}"
          state: "{{ kea_want_dhcp_ddns | ternary('started', 'stopped') }}"
          masked: no
          daemon_reload: true

      - name: reload systemd service
        systemd:
          name: "{{ kea_dhcp_ddns_service_name }}.service"
          state: restarted
          daemon_reload: true
        when: kea_want_dhcp_ddns and (t_kea_service_ddns_conf.changed or t_kea_conf_kea_ddns.changed)


  when:
    - kea_service_type == 'systemd'
