---

- block:
    - name: "get zfs associated dataset for {{ dataset.name | dirname }}"
      shell: zfs list -H "{{ dataset.name | dirname }}" | awk '$5 == "{{ dataset.name | dirname }}" { print $1 }'
      register: try_zfs_parent_dataset
      changed_when: no

    - name: "setup zfs dataset for {{ dataset.name }}"
      zfs:
        name: "{{ try_zfs_parent_dataset.stdout }}/{{ dataset.name | basename }}"
        state: present
        extra_zfs_properties: "{{ dataset.properties | d(zfs_dataset_default_properties) | d(omit) }}"
      when:
        - try_zfs_parent_dataset.rc == 0
        - try_zfs_parent_dataset.stdout != ""

  when: try_zfs | default(true)
